# Model settings
model:
  path: models/yolov5/yolov5s.onnx
  input_size: 256
  confidence_threshold: 0.6
  nms_threshold: 0.45
  allowed_classes:
    - person

# Camera settings
camera:
  width: 480
  height: 360

# Runtime settings
runtime:
  show_fps: true
  save_detection_images: true
